import { render } from "@testing-library/react";
import RootLayout, { metadata } from "../app/layout";

// stupidest unit test ever JUST to get 100% COVERAGE

jest.mock("next/font/google", () => ({
    Geist: () => ({ variable: "--font-geist-sans" }),
    Geist_Mono: () => ({ variable: "--font-geist-mono" }),
}));

describe("RootLayout Statements", () => {
    it("executes all statements including metadata and layout", () => {
        expect(metadata.title).toBe("Create Next App");
        expect(metadata.description).toBe("Generated by create next app");

        const { getByText } = render(
            <RootLayout>
                <div data-testid="child">Check Statements</div>
            </RootLayout>
        );

        expect(getByText("Check Statements")).toBeInTheDocument();
    });
});